config/routes.rb
Rails.application.routes.draw do

  root 'videos#index'

  resources :videos

end

app/models/video.rb
class Video < ActiveRecord::Base

  paginates_per 5

  has_attached_file :attachment, 
    styles: { medium: { :geometry => "640x480", :format => 'mp4' },
              thumb: { geometry: "150x100", :format => 'jpg' }
    }, 
    processors: [:transcoder]
  
  validates_attachment :attachment, presence: true,
    content_type: { content_type: "video/mp4" },
    size: { in: 0..50.megabytes }
  validates :title, presence: true

  before_create :set_defaults

  def set_defaults
    if self.attachment
      metadata = eval(self.attachment_meta)
      file_name_details = self.attachment_file_name.split('.')
      self.title ||= file_name_details.first.titleize
      self.format = file_name_details.last.titleize
      self.length = metadata[:duration].round
    end
  end

end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def new
    @video = Video.new
  end

  def create
    respond_to do |format|
      @video = Video.new(video_params)
      if @video.save
        flash[:notice] = 'video saved'
        format.html { redirect_to @video }
        format.js
      else
        flash[:notice] = 'Error messages: ' + @video.errors.full_messages.join(', ')
        format.html { render 'index' }
      end
    end
  end

  def index
    @video = Video.new
    @videos = Video.all.order(created_at: :desc).page params[:page]
  end

  def show
    @video = Video.find(params[:id])
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
    @video = Video.find(params[:id])
    if @video.update_attributes(video_params)
      redirect_to videos_path, notice: "Video was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    redirect_to videos_path, notice: "Video '#{@video.title}' deleted."
  end

  private

  def video_params
    params.require(:video).permit(:attachment, :title, :length, :format)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-dark bg-success">
  <div class="nav navbar-nav">
    <a class="nav-item nav-link active" href="/videos">VidUp</a>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vidup</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'layouts/nav'  %>
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, id: "flash_#{name}", class: 'alert-info text-xs-center' %>
<% end %>
<div class="container-fluid">
  <%= yield %>
</div>

</body>
</html>

app/views/videos/_form.html.erb
<%= form_for @video, html: {id: 'video-form'} do |f| %>
  <div class='form-group'>
    <%= f.label :title %><br />
    <%= f.text_field :title, id: 'title-field', class: 'form-control' %>
  </div>
  <div class='form-group'>
    <% if @video.attachment.present? %>
      <%= @video.attachment_file_name %>
    <% else %>
      <%= f.file_field :attachment, id: 'file-field' %>
    <% end %>
  </div>
  <div>
    <%= f.submit "Submit", id: 'submit', class: "btn btn-primary-outline" %>
    <%= link_to 'Cancel', videos_path, class: "btn btn-danger-outline" %>
  </div>
<% end %>

app/views/videos/_video.html.erb
<div class="video text-xs-center">
  <% if video %>
    <div class="col-md-4">
      <h6 class="title"><%= video.title %></h6>
      <%= link_to image_tag(video.attachment.url(:thumb)), video if video.attachment? %>
      <p class="card-text"><%= video.length.to_i %> sec | <%= video.format %></p>
      <p class="actions text-xs-center">
        <%= link_to "edit", edit_video_path(video) %> |
        <%= link_to "remove", video, :confirm => 'Are you sure?', :method => :delete %>
      </p>
    </div>
  <% end %>

</div>

app/views/videos/create.js.erb
<% if @video.new_record? %>
  $('.alert-info').append("Failed to upload: <%= j @video.errors.full_messages.join(', ').html_safe %>");
<% else %>
  $('#latest-video').prepend('<%= j render @video %>');
<% end %>

app/views/videos/edit.html.erb
<div class="row">
  <div class="col-md-8">
    <%= link_to '< back', videos_path %>
    <%= video_tag @video.attachment.url, controls: true, style: "max-width: 100%;" %>
  </div>
  <div class="col-md-4">
    <h3>Edit video</h3>
    <%= render partial: 'form', locals: {video: @video} %>
  </div>
</div>

app/views/videos/index.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>Videos</h1>
    <div id='latest-video'></div>
    <% if @videos.present? %>
      <%= @videos.each_slice(3) do |video| %>
        <div id="new-videos row">
          <%= render partial: 'video', collection: video, as: :video %>
        </div>
      <% end %>
    <% else %>
      <h3>No videos have been added</h3>
      <p>Use the form to add some now!</p>
    <% end %>
  </div>
  <div class="col-md-4">
    <div id="loading-wrapper" style = "display: none;">
      <progress value="0" max="100" class="progress progress-info progress-animated"></progress>
      <div>
        <span id="percent"></span><span id='time'></span>
      </div>
    </div>​

    <script id="template-upload" type="text/x-tmpl">
    </script>
    <h3>Submit new</h3>
    <%= render partial: 'form', locals: {video: @video} %>
  </div>
</div>
<div class="row">
  <div class="col-md-8">
    <div class="text-xs-center">
      <%= paginate @videos if @videos %>
    </div>
  </div>
</div>

app/views/videos/show.html.erb
<%= link_to '< back', videos_path %>
<h2 class='text-xs-center'><%= @video.title %></h2>
<%= video_tag @video.attachment.url, controls: true, style: "max-width: 100%;" %>